### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by dewarian** [ofahchouch-gh/movie-picker#1]
`npm start` results in an error
According to the terminal output this happens after the step
'node ./dist/bin/www'
and continues with **_DetailService.default is not a constructor**
```ZSH
controllers/movie/DetailController.js:26
    this.detailService = new _DetailService["default"]();
```

I'll add the debug log for further insight.
[ofahchouch-gh-2021-03-12T09_06_18_337Z-debug.log](https://github.com/ofahchouch-gh/movie-picker/files/6128851/ofahchouch-gh-2021-03-12T09_06_18_337Z-debug.log)

Might be the babel issue you have been talking about. As it has problems with the new keyword?

**Comment by ofahchouch-gh** [comment]
Yeah, i have no clue how to solve it. Maybe Derek can help me later with it.
