### ISSUE TITLE
npm scripts

### ISSUE THREAD

**Issue by dewarian** [ofahchouch-gh/movie-picker#3]
Looks good, nice that you have customized nodemon, didn't know you could do that.
https://github.com/ofahchouch-gh/movie-picker/blob/b00a52a0a9a4b7455d7be82cc0fa2a14337149a3/package.json#L5

With the scripts, I am wondering, would it be possible for you to use the pre- and post- npm hooks? This allows you to run just e.g. `npm run build`. and in the background, npm will fire off prebuild, build, and postbuild. This could clean the up the amount of concatenation you would have to do.

**Comment by ofahchouch-gh** [comment]
Thanks, yes you are right. Pre and postbuild is cleaner.
