### ISSUE TITLE
views template

### ISSUE THREAD

**Issue by dewarian** [ofahchouch-gh/movie-picker#4]
https://github.com/ofahchouch-gh/movie-picker/blob/b00a52a0a9a4b7455d7be82cc0fa2a14337149a3/src/views/index.pug#L6

Maybe it is an idea to create a reference path to the public folder in the app.js, as right now you have a track of `../` in every public import.

I see you did something with it but commented it out for testing it on the VPS.

**Comment by ofahchouch-gh** [comment]
Thanks, gefixed :)!
