### ISSUE TITLE
MVC pattern

### ISSUE THREAD

**Issue by dewarian** [ofahchouch-gh/movie-picker#5]
Nice work on the MVC pattern (+ service layer) and splitting the logic in class-based constructors. It is 10 times more work but allows for a clean approach and template code that is easily reusable.
🎉🎉🎉
Would love to see it running when you have more time.

**Comment by ofahchouch-gh** [comment]
Thanks, i have used MVC in the past. Would like to learn more front-end though during the minor :)!

I found the issue, i accidentally removed the file DetailService. So it's no up and running on: http://5.189.146.202:3002/
