### ISSUE TITLE
Code review week 1

### ISSUE THREAD

**Issue by RobinFrugte97** [ofahchouch-gh/movie-picker#6]
Yo Oussama!

Goed begin van je readme! Je hebt je packages al benoemd en gelinkt naar de docs! Erg netjes. Kijk wat je nogmeer uit je WAFS readme kan halen om het wat aan te vullen. Misschien gaat die vlieger niet op omdat je een andere API hebt, maar maak het dan wat meer visueel.

Ik zie dat je met een andere api bezig bent, goed dat je het al hebt staan. 

Goeie script chain heb je al. 

Alles in modules ook.

Lekker bezig man, heb weinig toe te voegen. Weet dat je geëxperimenteerd hebt met webpack. Documenteer dat soort dingen ook, dan weten we wat voor keuzes je hebt gemaakt in je proces. Je hebt misschien ook bewust voor pug gekozen i.p.v. ejs. Documenteer!

Lekker door met service worker volgende week.

**Comment by ofahchouch-gh** [comment]
Thanks voor het advies! Zal de verbeterpunten oppakken :D.

Fijn weekend!
